/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 40
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_POUND = 2,
  anon_sym_HELP = 3,
  anon_sym_TYPE = 4,
  aux_sym_comment_token1 = 5,
  anon_sym_counter = 6,
  anon_sym_gauge = 7,
  anon_sym_histogram = 8,
  anon_sym_summary = 9,
  anon_sym_untyped = 10,
  sym_metric_help = 11,
  sym_metric_name = 12,
  anon_sym_LBRACE = 13,
  anon_sym_COMMA = 14,
  anon_sym_RBRACE = 15,
  anon_sym_EQ = 16,
  anon_sym_DQUOTE = 17,
  sym_label_name = 18,
  sym_label_value = 19,
  anon_sym_NaN = 20,
  anon_sym_PLUSInf = 21,
  anon_sym_DASHInf = 22,
  sym__float_value = 23,
  sym_timestamp = 24,
  sym_source_file = 25,
  sym__line = 26,
  sym__comment_line = 27,
  sym_help_line = 28,
  sym_type_line = 29,
  sym_comment = 30,
  sym_metric_type = 31,
  sym_metric_line = 32,
  sym_label_set = 33,
  sym_label = 34,
  sym_metric_value = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym_label_set_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_POUND] = "#",
  [anon_sym_HELP] = "HELP",
  [anon_sym_TYPE] = "TYPE",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_counter] = "counter",
  [anon_sym_gauge] = "gauge",
  [anon_sym_histogram] = "histogram",
  [anon_sym_summary] = "summary",
  [anon_sym_untyped] = "untyped",
  [sym_metric_help] = "metric_help",
  [sym_metric_name] = "metric_name",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_DQUOTE] = "\"",
  [sym_label_name] = "label_name",
  [sym_label_value] = "label_value",
  [anon_sym_NaN] = "NaN",
  [anon_sym_PLUSInf] = "+Inf",
  [anon_sym_DASHInf] = "-Inf",
  [sym__float_value] = "_float_value",
  [sym_timestamp] = "timestamp",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym__comment_line] = "_comment_line",
  [sym_help_line] = "help_line",
  [sym_type_line] = "type_line",
  [sym_comment] = "comment",
  [sym_metric_type] = "metric_type",
  [sym_metric_line] = "metric_line",
  [sym_label_set] = "label_set",
  [sym_label] = "label",
  [sym_metric_value] = "metric_value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_label_set_repeat1] = "label_set_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_HELP] = anon_sym_HELP,
  [anon_sym_TYPE] = anon_sym_TYPE,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_counter] = anon_sym_counter,
  [anon_sym_gauge] = anon_sym_gauge,
  [anon_sym_histogram] = anon_sym_histogram,
  [anon_sym_summary] = anon_sym_summary,
  [anon_sym_untyped] = anon_sym_untyped,
  [sym_metric_help] = sym_metric_help,
  [sym_metric_name] = sym_metric_name,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_label_name] = sym_label_name,
  [sym_label_value] = sym_label_value,
  [anon_sym_NaN] = anon_sym_NaN,
  [anon_sym_PLUSInf] = anon_sym_PLUSInf,
  [anon_sym_DASHInf] = anon_sym_DASHInf,
  [sym__float_value] = sym__float_value,
  [sym_timestamp] = sym_timestamp,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym__comment_line] = sym__comment_line,
  [sym_help_line] = sym_help_line,
  [sym_type_line] = sym_type_line,
  [sym_comment] = sym_comment,
  [sym_metric_type] = sym_metric_type,
  [sym_metric_line] = sym_metric_line,
  [sym_label_set] = sym_label_set,
  [sym_label] = sym_label,
  [sym_metric_value] = sym_metric_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_label_set_repeat1] = aux_sym_label_set_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_HELP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TYPE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_counter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_gauge] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_histogram] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_summary] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_untyped] = {
    .visible = true,
    .named = false,
  },
  [sym_metric_help] = {
    .visible = true,
    .named = true,
  },
  [sym_metric_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_label_name] = {
    .visible = true,
    .named = true,
  },
  [sym_label_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_NaN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUSInf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASHInf] = {
    .visible = true,
    .named = false,
  },
  [sym__float_value] = {
    .visible = false,
    .named = true,
  },
  [sym_timestamp] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__comment_line] = {
    .visible = false,
    .named = true,
  },
  [sym_help_line] = {
    .visible = true,
    .named = true,
  },
  [sym_type_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_metric_type] = {
    .visible = true,
    .named = true,
  },
  [sym_metric_line] = {
    .visible = true,
    .named = true,
  },
  [sym_label_set] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_metric_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_label_set_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(52);
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == ' ') SKIP(0);
      if (lookahead == '"') ADVANCE(77);
      if (lookahead == '#') ADVANCE(54);
      if (lookahead == '+') ADVANCE(3);
      if (lookahead == ',') ADVANCE(74);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '.') ADVANCE(48);
      if (lookahead == '=') ADVANCE(76);
      if (lookahead == 'H') ADVANCE(5);
      if (lookahead == 'N') ADVANCE(12);
      if (lookahead == 'T') ADVANCE(11);
      if (lookahead == 'c') ADVANCE(32);
      if (lookahead == 'g') ADVANCE(14);
      if (lookahead == 'h') ADVANCE(24);
      if (lookahead == 's') ADVANCE(42);
      if (lookahead == 'u') ADVANCE(28);
      if (lookahead == '{') ADVANCE(73);
      if (lookahead == '}') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 1:
      if (lookahead == ' ') SKIP(1);
      if (lookahead == '+') ADVANCE(3);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '.') ADVANCE(48);
      if (lookahead == 'N') ADVANCE(12);
      if (lookahead == '{') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 2:
      if (lookahead == ' ') SKIP(2);
      if (lookahead == '}') ADVANCE(75);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(78);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(48);
      if (lookahead == 'I') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(48);
      if (lookahead == 'I') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 5:
      if (lookahead == 'E') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'E') ADVANCE(56);
      END_STATE();
    case 7:
      if (lookahead == 'L') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'N') ADVANCE(81);
      END_STATE();
    case 9:
      if (lookahead == 'P') ADVANCE(55);
      END_STATE();
    case 10:
      if (lookahead == 'P') ADVANCE(6);
      END_STATE();
    case 11:
      if (lookahead == 'Y') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(36);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead == 'd') ADVANCE(69);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 20:
      if (lookahead == 'f') ADVANCE(82);
      END_STATE();
    case 21:
      if (lookahead == 'f') ADVANCE(83);
      END_STATE();
    case 22:
      if (lookahead == 'g') ADVANCE(17);
      END_STATE();
    case 23:
      if (lookahead == 'g') ADVANCE(37);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 25:
      if (lookahead == 'm') ADVANCE(67);
      END_STATE();
    case 26:
      if (lookahead == 'm') ADVANCE(27);
      END_STATE();
    case 27:
      if (lookahead == 'm') ADVANCE(13);
      END_STATE();
    case 28:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 32:
      if (lookahead == 'o') ADVANCE(44);
      END_STATE();
    case 33:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 34:
      if (lookahead == 'p') ADVANCE(18);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(65);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 38:
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 42:
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 43:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 44:
      if (lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 45:
      if (lookahead == 'y') ADVANCE(34);
      END_STATE();
    case 46:
      if (lookahead == 'y') ADVANCE(68);
      END_STATE();
    case 47:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      END_STATE();
    case 48:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      END_STATE();
    case 49:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      END_STATE();
    case 50:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(80);
      END_STATE();
    case 51:
      if (eof) ADVANCE(52);
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == ' ') SKIP(51);
      if (lookahead == '#') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(87);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_HELP);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_TYPE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == ' ') ADVANCE(57);
      if (lookahead == 'H') ADVANCE(59);
      if (lookahead == 'T') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == 'E') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == 'E') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == 'L') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == 'P') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == 'P') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == 'Y') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_counter);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_gauge);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_histogram);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_summary);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_untyped);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_metric_help);
      if (lookahead == ' ') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(71);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_metric_help);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_metric_name);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_label_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_label_value);
      if (lookahead == ' ') ADVANCE(79);
      if (lookahead == '\\') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(80);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_label_value);
      if (lookahead == '\\') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_NaN);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_PLUSInf);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_DASHInf);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym__float_value);
      if (lookahead == '.') ADVANCE(48);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym__float_value);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym__float_value);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_timestamp);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(87);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 51},
  [2] = {.lex_state = 51},
  [3] = {.lex_state = 51},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 51},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 57},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 51},
  [20] = {.lex_state = 51},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 51},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 51},
  [26] = {.lex_state = 51},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 70},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 79},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_HELP] = ACTIONS(1),
    [anon_sym_TYPE] = ACTIONS(1),
    [anon_sym_counter] = ACTIONS(1),
    [anon_sym_gauge] = ACTIONS(1),
    [anon_sym_histogram] = ACTIONS(1),
    [anon_sym_summary] = ACTIONS(1),
    [anon_sym_untyped] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_NaN] = ACTIONS(1),
    [anon_sym_PLUSInf] = ACTIONS(1),
    [anon_sym_DASHInf] = ACTIONS(1),
    [sym__float_value] = ACTIONS(1),
    [sym_timestamp] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(38),
    [sym__line] = STATE(27),
    [sym__comment_line] = STATE(27),
    [sym_help_line] = STATE(27),
    [sym_type_line] = STATE(27),
    [sym_comment] = STATE(27),
    [sym_metric_line] = STATE(27),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [sym_metric_name] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      anon_sym_LF,
    ACTIONS(16), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_metric_name,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(27), 6,
      sym__line,
      sym__comment_line,
      sym_help_line,
      sym_type_line,
      sym_comment,
      sym_metric_line,
  [24] = 6,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_metric_name,
    ACTIONS(22), 1,
      ts_builtin_sym_end,
    ACTIONS(24), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(27), 6,
      sym__line,
      sym__comment_line,
      sym_help_line,
      sym_type_line,
      sym_comment,
      sym_metric_line,
  [48] = 4,
    ACTIONS(26), 1,
      anon_sym_LBRACE,
    STATE(6), 1,
      sym_label_set,
    STATE(20), 1,
      sym_metric_value,
    ACTIONS(28), 4,
      anon_sym_NaN,
      anon_sym_PLUSInf,
      anon_sym_DASHInf,
      sym__float_value,
  [64] = 2,
    STATE(33), 1,
      sym_metric_type,
    ACTIONS(30), 5,
      anon_sym_counter,
      anon_sym_gauge,
      anon_sym_histogram,
      anon_sym_summary,
      anon_sym_untyped,
  [75] = 2,
    STATE(19), 1,
      sym_metric_value,
    ACTIONS(28), 4,
      anon_sym_NaN,
      anon_sym_PLUSInf,
      anon_sym_DASHInf,
      sym__float_value,
  [85] = 1,
    ACTIONS(11), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      sym_metric_name,
  [92] = 1,
    ACTIONS(32), 4,
      anon_sym_NaN,
      anon_sym_PLUSInf,
      anon_sym_DASHInf,
      sym__float_value,
  [99] = 1,
    ACTIONS(34), 4,
      anon_sym_NaN,
      anon_sym_PLUSInf,
      anon_sym_DASHInf,
      sym__float_value,
  [106] = 1,
    ACTIONS(36), 4,
      anon_sym_NaN,
      anon_sym_PLUSInf,
      anon_sym_DASHInf,
      sym__float_value,
  [113] = 1,
    ACTIONS(38), 4,
      anon_sym_NaN,
      anon_sym_PLUSInf,
      anon_sym_DASHInf,
      sym__float_value,
  [120] = 3,
    ACTIONS(40), 1,
      anon_sym_COMMA,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      aux_sym_label_set_repeat1,
  [130] = 3,
    ACTIONS(45), 1,
      anon_sym_HELP,
    ACTIONS(47), 1,
      anon_sym_TYPE,
    ACTIONS(49), 1,
      aux_sym_comment_token1,
  [140] = 3,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    STATE(17), 1,
      aux_sym_label_set_repeat1,
  [150] = 3,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    ACTIONS(57), 1,
      sym_label_name,
    STATE(23), 1,
      sym_label,
  [160] = 3,
    ACTIONS(57), 1,
      sym_label_name,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    STATE(14), 1,
      sym_label,
  [170] = 3,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    ACTIONS(61), 1,
      anon_sym_COMMA,
    STATE(12), 1,
      aux_sym_label_set_repeat1,
  [180] = 3,
    ACTIONS(57), 1,
      sym_label_name,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    STATE(23), 1,
      sym_label,
  [190] = 2,
    ACTIONS(65), 1,
      anon_sym_LF,
    ACTIONS(67), 1,
      sym_timestamp,
  [197] = 2,
    ACTIONS(69), 1,
      anon_sym_LF,
    ACTIONS(71), 1,
      sym_timestamp,
  [204] = 2,
    ACTIONS(57), 1,
      sym_label_name,
    STATE(23), 1,
      sym_label,
  [211] = 1,
    ACTIONS(73), 2,
      anon_sym_LF,
      sym_timestamp,
  [216] = 1,
    ACTIONS(43), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [221] = 1,
    ACTIONS(75), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [226] = 1,
    ACTIONS(77), 1,
      sym_metric_name,
  [230] = 1,
    ACTIONS(79), 1,
      sym_metric_name,
  [234] = 1,
    ACTIONS(81), 1,
      anon_sym_LF,
  [238] = 1,
    ACTIONS(83), 1,
      sym_metric_help,
  [242] = 1,
    ACTIONS(85), 1,
      anon_sym_EQ,
  [246] = 1,
    ACTIONS(65), 1,
      anon_sym_LF,
  [250] = 1,
    ACTIONS(87), 1,
      anon_sym_LF,
  [254] = 1,
    ACTIONS(89), 1,
      anon_sym_LF,
  [258] = 1,
    ACTIONS(91), 1,
      anon_sym_LF,
  [262] = 1,
    ACTIONS(93), 1,
      sym_label_value,
  [266] = 1,
    ACTIONS(95), 1,
      anon_sym_LF,
  [270] = 1,
    ACTIONS(97), 1,
      anon_sym_LF,
  [274] = 1,
    ACTIONS(99), 1,
      anon_sym_DQUOTE,
  [278] = 1,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
  [282] = 1,
    ACTIONS(103), 1,
      anon_sym_DQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 24,
  [SMALL_STATE(4)] = 48,
  [SMALL_STATE(5)] = 64,
  [SMALL_STATE(6)] = 75,
  [SMALL_STATE(7)] = 85,
  [SMALL_STATE(8)] = 92,
  [SMALL_STATE(9)] = 99,
  [SMALL_STATE(10)] = 106,
  [SMALL_STATE(11)] = 113,
  [SMALL_STATE(12)] = 120,
  [SMALL_STATE(13)] = 130,
  [SMALL_STATE(14)] = 140,
  [SMALL_STATE(15)] = 150,
  [SMALL_STATE(16)] = 160,
  [SMALL_STATE(17)] = 170,
  [SMALL_STATE(18)] = 180,
  [SMALL_STATE(19)] = 190,
  [SMALL_STATE(20)] = 197,
  [SMALL_STATE(21)] = 204,
  [SMALL_STATE(22)] = 211,
  [SMALL_STATE(23)] = 216,
  [SMALL_STATE(24)] = 221,
  [SMALL_STATE(25)] = 226,
  [SMALL_STATE(26)] = 230,
  [SMALL_STATE(27)] = 234,
  [SMALL_STATE(28)] = 238,
  [SMALL_STATE(29)] = 242,
  [SMALL_STATE(30)] = 246,
  [SMALL_STATE(31)] = 250,
  [SMALL_STATE(32)] = 254,
  [SMALL_STATE(33)] = 258,
  [SMALL_STATE(34)] = 262,
  [SMALL_STATE(35)] = 266,
  [SMALL_STATE(36)] = 270,
  [SMALL_STATE(37)] = 274,
  [SMALL_STATE(38)] = 278,
  [SMALL_STATE(39)] = 282,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [16] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_set, 2, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_set, 3, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_set, 4, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_set, 5, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_label_set_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_label_set_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metric_line, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metric_line, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metric_value, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 5, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_help_line, 4, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metric_type, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_line, 4, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metric_line, 4, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [101] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_prom(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "prom",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
