/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 39
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_POUND = 2,
  anon_sym_HELP = 3,
  anon_sym_TYPE = 4,
  sym_comment = 5,
  anon_sym_counter = 6,
  anon_sym_gauge = 7,
  anon_sym_histogram = 8,
  anon_sym_summary = 9,
  anon_sym_untyped = 10,
  sym_metric_help = 11,
  sym_metric_name = 12,
  anon_sym_LBRACE = 13,
  anon_sym_COMMA = 14,
  anon_sym_RBRACE = 15,
  anon_sym_EQ = 16,
  anon_sym_DQUOTE = 17,
  sym_label_name = 18,
  sym_label_value = 19,
  sym_metric_value = 20,
  sym_timestamp = 21,
  sym_source_file = 22,
  sym__line = 23,
  sym__comment_line = 24,
  sym_help_line = 25,
  sym_type_line = 26,
  sym_metric_type = 27,
  sym_metric_line = 28,
  sym_label_set = 29,
  sym_label = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym_label_set_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_POUND] = "#",
  [anon_sym_HELP] = "HELP",
  [anon_sym_TYPE] = "TYPE",
  [sym_comment] = "comment",
  [anon_sym_counter] = "counter",
  [anon_sym_gauge] = "gauge",
  [anon_sym_histogram] = "histogram",
  [anon_sym_summary] = "summary",
  [anon_sym_untyped] = "untyped",
  [sym_metric_help] = "metric_help",
  [sym_metric_name] = "metric_name",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_DQUOTE] = "\"",
  [sym_label_name] = "label_name",
  [sym_label_value] = "label_value",
  [sym_metric_value] = "metric_value",
  [sym_timestamp] = "timestamp",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym__comment_line] = "_comment_line",
  [sym_help_line] = "help_line",
  [sym_type_line] = "type_line",
  [sym_metric_type] = "metric_type",
  [sym_metric_line] = "metric_line",
  [sym_label_set] = "label_set",
  [sym_label] = "label",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_label_set_repeat1] = "label_set_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_HELP] = anon_sym_HELP,
  [anon_sym_TYPE] = anon_sym_TYPE,
  [sym_comment] = sym_comment,
  [anon_sym_counter] = anon_sym_counter,
  [anon_sym_gauge] = anon_sym_gauge,
  [anon_sym_histogram] = anon_sym_histogram,
  [anon_sym_summary] = anon_sym_summary,
  [anon_sym_untyped] = anon_sym_untyped,
  [sym_metric_help] = sym_metric_help,
  [sym_metric_name] = sym_metric_name,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_label_name] = sym_label_name,
  [sym_label_value] = sym_label_value,
  [sym_metric_value] = sym_metric_value,
  [sym_timestamp] = sym_timestamp,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym__comment_line] = sym__comment_line,
  [sym_help_line] = sym_help_line,
  [sym_type_line] = sym_type_line,
  [sym_metric_type] = sym_metric_type,
  [sym_metric_line] = sym_metric_line,
  [sym_label_set] = sym_label_set,
  [sym_label] = sym_label,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_label_set_repeat1] = aux_sym_label_set_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_HELP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TYPE] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_counter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_gauge] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_histogram] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_summary] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_untyped] = {
    .visible = true,
    .named = false,
  },
  [sym_metric_help] = {
    .visible = true,
    .named = true,
  },
  [sym_metric_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_label_name] = {
    .visible = true,
    .named = true,
  },
  [sym_label_value] = {
    .visible = true,
    .named = true,
  },
  [sym_metric_value] = {
    .visible = true,
    .named = true,
  },
  [sym_timestamp] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__comment_line] = {
    .visible = false,
    .named = true,
  },
  [sym_help_line] = {
    .visible = true,
    .named = true,
  },
  [sym_type_line] = {
    .visible = true,
    .named = true,
  },
  [sym_metric_type] = {
    .visible = true,
    .named = true,
  },
  [sym_metric_line] = {
    .visible = true,
    .named = true,
  },
  [sym_label_set] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_label_set_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(44);
      if (lookahead == '\n') ADVANCE(45);
      if (lookahead == ' ') SKIP(0);
      if (lookahead == '"') ADVANCE(69);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == ',') ADVANCE(66);
      if (lookahead == '.') ADVANCE(40);
      if (lookahead == '=') ADVANCE(68);
      if (lookahead == 'H') ADVANCE(3);
      if (lookahead == 'T') ADVANCE(8);
      if (lookahead == 'c') ADVANCE(24);
      if (lookahead == 'g') ADVANCE(10);
      if (lookahead == 'h') ADVANCE(18);
      if (lookahead == 's') ADVANCE(34);
      if (lookahead == 'u') ADVANCE(22);
      if (lookahead == '{') ADVANCE(65);
      if (lookahead == '}') ADVANCE(67);
      if (('+' <= lookahead && lookahead <= '-')) ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(45);
      if (lookahead == ' ') SKIP(1);
      if (lookahead == '}') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 3:
      if (lookahead == 'E') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == 'E') ADVANCE(48);
      END_STATE();
    case 5:
      if (lookahead == 'L') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == 'P') ADVANCE(47);
      END_STATE();
    case 7:
      if (lookahead == 'P') ADVANCE(4);
      END_STATE();
    case 8:
      if (lookahead == 'Y') ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(35);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(61);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == 'g') ADVANCE(13);
      END_STATE();
    case 17:
      if (lookahead == 'g') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(30);
      END_STATE();
    case 19:
      if (lookahead == 'm') ADVANCE(59);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(9);
      END_STATE();
    case 21:
      if (lookahead == 'm') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 26:
      if (lookahead == 'p') ADVANCE(14);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(57);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(38);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 30:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 34:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 36:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 37:
      if (lookahead == 'y') ADVANCE(26);
      END_STATE();
    case 38:
      if (lookahead == 'y') ADVANCE(60);
      END_STATE();
    case 39:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 40:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 41:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 42:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 43:
      if (eof) ADVANCE(44);
      if (lookahead == '\n') ADVANCE(45);
      if (lookahead == ' ') SKIP(43);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == '.') ADVANCE(40);
      if (lookahead == '{') ADVANCE(65);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_HELP);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_TYPE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == ' ') ADVANCE(49);
      if (lookahead == 'H') ADVANCE(51);
      if (lookahead == 'T') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'E') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'E') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'L') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'P') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'P') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'Y') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_counter);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_gauge);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_histogram);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_summary);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_untyped);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_metric_help);
      if (lookahead == ' ') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_metric_help);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_metric_name);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_label_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_label_value);
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == '\\') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(72);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_label_value);
      if (lookahead == '\\') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_metric_value);
      if (lookahead == '.') ADVANCE(40);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_metric_value);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_metric_value);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_timestamp);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 43},
  [2] = {.lex_state = 43},
  [3] = {.lex_state = 43},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 49},
  [6] = {.lex_state = 43},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 43},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 62},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 43},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 43},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 43},
  [31] = {.lex_state = 43},
  [32] = {.lex_state = 71},
  [33] = {.lex_state = 43},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 43},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 43},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_HELP] = ACTIONS(1),
    [anon_sym_TYPE] = ACTIONS(1),
    [anon_sym_counter] = ACTIONS(1),
    [anon_sym_gauge] = ACTIONS(1),
    [anon_sym_histogram] = ACTIONS(1),
    [anon_sym_summary] = ACTIONS(1),
    [anon_sym_untyped] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_metric_value] = ACTIONS(1),
    [sym_timestamp] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(20),
    [sym__line] = STATE(25),
    [sym__comment_line] = STATE(25),
    [sym_metric_line] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [sym_metric_name] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_metric_name,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      anon_sym_LF,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(25), 3,
      sym__line,
      sym__comment_line,
      sym_metric_line,
  [21] = 6,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_LF,
    ACTIONS(20), 1,
      anon_sym_POUND,
    ACTIONS(23), 1,
      sym_metric_name,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(25), 3,
      sym__line,
      sym__comment_line,
      sym_metric_line,
  [42] = 2,
    STATE(28), 1,
      sym_metric_type,
    ACTIONS(26), 5,
      anon_sym_counter,
      anon_sym_gauge,
      anon_sym_histogram,
      anon_sym_summary,
      anon_sym_untyped,
  [53] = 4,
    ACTIONS(28), 1,
      anon_sym_HELP,
    ACTIONS(30), 1,
      anon_sym_TYPE,
    ACTIONS(32), 1,
      sym_comment,
    STATE(36), 2,
      sym_help_line,
      sym_type_line,
  [67] = 1,
    ACTIONS(15), 4,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      sym_metric_name,
  [74] = 3,
    ACTIONS(34), 1,
      anon_sym_RBRACE,
    ACTIONS(36), 1,
      sym_label_name,
    STATE(9), 1,
      sym_label,
  [84] = 3,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(40), 1,
      sym_metric_value,
    STATE(30), 1,
      sym_label_set,
  [94] = 3,
    ACTIONS(42), 1,
      anon_sym_COMMA,
    ACTIONS(44), 1,
      anon_sym_RBRACE,
    STATE(11), 1,
      aux_sym_label_set_repeat1,
  [104] = 3,
    ACTIONS(36), 1,
      sym_label_name,
    ACTIONS(46), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      sym_label,
  [114] = 3,
    ACTIONS(46), 1,
      anon_sym_RBRACE,
    ACTIONS(48), 1,
      anon_sym_COMMA,
    STATE(13), 1,
      aux_sym_label_set_repeat1,
  [124] = 3,
    ACTIONS(36), 1,
      sym_label_name,
    ACTIONS(50), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      sym_label,
  [134] = 3,
    ACTIONS(52), 1,
      anon_sym_COMMA,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    STATE(13), 1,
      aux_sym_label_set_repeat1,
  [144] = 2,
    ACTIONS(57), 1,
      anon_sym_LF,
    ACTIONS(59), 1,
      sym_timestamp,
  [151] = 2,
    ACTIONS(61), 1,
      anon_sym_LF,
    ACTIONS(63), 1,
      sym_timestamp,
  [158] = 1,
    ACTIONS(55), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [163] = 2,
    ACTIONS(36), 1,
      sym_label_name,
    STATE(16), 1,
      sym_label,
  [170] = 1,
    ACTIONS(65), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [175] = 1,
    ACTIONS(67), 1,
      sym_metric_help,
  [179] = 1,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
  [183] = 1,
    ACTIONS(71), 1,
      sym_metric_value,
  [187] = 1,
    ACTIONS(73), 1,
      anon_sym_EQ,
  [191] = 1,
    ACTIONS(75), 1,
      sym_metric_name,
  [195] = 1,
    ACTIONS(57), 1,
      anon_sym_LF,
  [199] = 1,
    ACTIONS(77), 1,
      anon_sym_LF,
  [203] = 1,
    ACTIONS(79), 1,
      anon_sym_LF,
  [207] = 1,
    ACTIONS(81), 1,
      anon_sym_LF,
  [211] = 1,
    ACTIONS(83), 1,
      anon_sym_LF,
  [215] = 1,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
  [219] = 1,
    ACTIONS(87), 1,
      sym_metric_value,
  [223] = 1,
    ACTIONS(89), 1,
      sym_metric_value,
  [227] = 1,
    ACTIONS(91), 1,
      sym_label_value,
  [231] = 1,
    ACTIONS(93), 1,
      sym_metric_value,
  [235] = 1,
    ACTIONS(95), 1,
      anon_sym_LF,
  [239] = 1,
    ACTIONS(97), 1,
      sym_metric_name,
  [243] = 1,
    ACTIONS(99), 1,
      anon_sym_LF,
  [247] = 1,
    ACTIONS(101), 1,
      anon_sym_DQUOTE,
  [251] = 1,
    ACTIONS(103), 1,
      sym_metric_value,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 21,
  [SMALL_STATE(4)] = 42,
  [SMALL_STATE(5)] = 53,
  [SMALL_STATE(6)] = 67,
  [SMALL_STATE(7)] = 74,
  [SMALL_STATE(8)] = 84,
  [SMALL_STATE(9)] = 94,
  [SMALL_STATE(10)] = 104,
  [SMALL_STATE(11)] = 114,
  [SMALL_STATE(12)] = 124,
  [SMALL_STATE(13)] = 134,
  [SMALL_STATE(14)] = 144,
  [SMALL_STATE(15)] = 151,
  [SMALL_STATE(16)] = 158,
  [SMALL_STATE(17)] = 163,
  [SMALL_STATE(18)] = 170,
  [SMALL_STATE(19)] = 175,
  [SMALL_STATE(20)] = 179,
  [SMALL_STATE(21)] = 183,
  [SMALL_STATE(22)] = 187,
  [SMALL_STATE(23)] = 191,
  [SMALL_STATE(24)] = 195,
  [SMALL_STATE(25)] = 199,
  [SMALL_STATE(26)] = 203,
  [SMALL_STATE(27)] = 207,
  [SMALL_STATE(28)] = 211,
  [SMALL_STATE(29)] = 215,
  [SMALL_STATE(30)] = 219,
  [SMALL_STATE(31)] = 223,
  [SMALL_STATE(32)] = 227,
  [SMALL_STATE(33)] = 231,
  [SMALL_STATE(34)] = 235,
  [SMALL_STATE(35)] = 239,
  [SMALL_STATE(36)] = 243,
  [SMALL_STATE(37)] = 247,
  [SMALL_STATE(38)] = 251,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [28] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [30] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [32] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_label_set_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_label_set_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metric_line, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metric_line, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 5, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [69] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_set, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_help_line, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metric_type, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_line, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_set, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_set, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metric_line, 4, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment_line, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_set, 5, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_prom(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "prom",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
